//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcNews.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NewsDbEntities : DbContext
    {
        public NewsDbEntities()
            : base("name=NewsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int sp_DeleteCategories(Nullable<int> cId)
        {
            var cIdParameter = cId.HasValue ?
                new ObjectParameter("CId", cId) :
                new ObjectParameter("CId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteCategories", cIdParameter);
        }
    
        public virtual int sp_DeleteNews(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteNews", idParameter);
        }
    
        public virtual int sp_InsertCategories(string categoryName)
        {
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("CategoryName", categoryName) :
                new ObjectParameter("CategoryName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertCategories", categoryNameParameter);
        }
    
        public virtual int sp_InsertNews(Nullable<int> cId, string newsTitle, string newsContent)
        {
            var cIdParameter = cId.HasValue ?
                new ObjectParameter("CId", cId) :
                new ObjectParameter("CId", typeof(int));
    
            var newsTitleParameter = newsTitle != null ?
                new ObjectParameter("NewsTitle", newsTitle) :
                new ObjectParameter("NewsTitle", typeof(string));
    
            var newsContentParameter = newsContent != null ?
                new ObjectParameter("NewsContent", newsContent) :
                new ObjectParameter("NewsContent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertNews", cIdParameter, newsTitleParameter, newsContentParameter);
        }
    
        public virtual ObjectResult<SelectCategoryObject> sp_SelectCategories()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectCategoryObject>("sp_SelectCategories");
        }
    
        public virtual ObjectResult<SelectCategoryObject> sp_SelectCategoryById(Nullable<int> cId)
        {
            var cIdParameter = cId.HasValue ?
                new ObjectParameter("CId", cId) :
                new ObjectParameter("CId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectCategoryObject>("sp_SelectCategoryById", cIdParameter);
        }
    
        public virtual ObjectResult<SelectNewsObject> sp_SelectNews()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectNewsObject>("sp_SelectNews");
        }
    
        public virtual ObjectResult<SelectNewsObject> sp_SelectNewsById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectNewsObject>("sp_SelectNewsById", idParameter);
        }
    
        public virtual int sp_UpdateNews(Nullable<int> id, Nullable<int> cId, string newsTitle, string newsContent)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var cIdParameter = cId.HasValue ?
                new ObjectParameter("CId", cId) :
                new ObjectParameter("CId", typeof(int));
    
            var newsTitleParameter = newsTitle != null ?
                new ObjectParameter("NewsTitle", newsTitle) :
                new ObjectParameter("NewsTitle", typeof(string));
    
            var newsContentParameter = newsContent != null ?
                new ObjectParameter("NewsContent", newsContent) :
                new ObjectParameter("NewsContent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateNews", idParameter, cIdParameter, newsTitleParameter, newsContentParameter);
        }
    }
}
